swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/account:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Account List
      description: API for fetching a list of user's accounts
      produces:
        - application/json
      responses:
        '200':
          description: Accounts fetched successfully
          schema:
            type: array
            items:
               $ref: '#/definitions/Accounts'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/account/transactions:
    get:
      security:
      - Bearer: []
      tags:
      - Account Module
      summary: Transaction List
      description: API for fetching the user's list of transactions for a specific account
      parameters:
        - in: body
          name: accountId
          required: true
          schema:
            type: object
            properties:
             accountId:
              type: string
          description: The ID of the transaction to return.
      produces:
          - application/json
      responses:
        '200':
          description: Transaction list fetched successfully
          schema:
              type: array
              items:
               $ref: '#/definitions/Transaction'
          
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/account/transactions/{transactionId}:
    put:
      security:
      - Bearer: []
      tags:
      - Account Module
      summary: Transaction Modification
      description: API for modifying a transaction's category or note
      parameters:
        - in: path
          name: transactionId
          required: true
          type: integer
          minimum: 1
          description: The ID of the transaction to return.
      produces:

      responses:
        '200':
          description: Transaction list fetched successfully
          schema:
              type: array
              items:
               $ref: '#/definitions/Transaction'
          
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  Accounts:
    type: object
    properties:
        accountId:
          type: string
        accountName:
          type: string
        balance:
          type: string
        description:
          type: string

  Transaction:
    type: object
    properties:
        transactionId:
          type: string
        date:
          type: string
        description:
          type: string
        category:
          type: string
        ammount:
          type: string
        note:
          type: string
